# Schema definitions for Whisper files. Entries are scanned in order,
# and first match wins. This file is scanned for changes every 60 seconds.
#
#  [name]
#  pattern = regex
#  retentions = timePerPoint:timeToStore, timePerPoint:timeToStore, ...

[carbon]
pattern = ^carbon\.
retentions = 60:90d

[default_1min_for_1day]
pattern = ^spring\.
retentions = 60s:1d, 5m:30d, 1h:1y

[default_10s_for_1h]
pattern = ^jvm\.
retentions = 10s:1h, 1m:7d, 10m:1y

[default_1min_for_7d]
pattern = ^http\.
retentions = 1m:7d, 5m:30d, 1h:1y

[default_1min_for_30d]
pattern = ^hikaricp\.
retentions = 1m:7d, 5m:30d, 1h:1y

[default_1min_for_7d]
pattern = ^tomcat\.
retentions = 1m:7d, 5m:30d, 1h:1y

[default_1min_for_7d]
pattern = ^datasource\.
retentions = 1m:7d, 5m:30d, 1h:1y

[default_5min_for_90d]
pattern = ^system\.
retentions = 5m:30d, 1h:1y

[default_1min_for_7d]
pattern = ^process\.
retentions = 1m:7d, 5m:30d, 1h:1y

[default_1min_for_7d]
pattern = ^logback\.
retentions = 1m:7d, 5m:30d, 1h:1y

# Catch-all for any metrics not matched above
[catch_all]
pattern = .*
retentions = 1m:7d, 5m:30d, 1h:1y